# Generated by Django 2.0.13 on 2019-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
