# Generated by Django 2.0.13 on 2019-03-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_money_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'ordering': ['-amount']},
        ),
    ]
